# -*- coding: utf-8 -*-
"""Crypto1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qap7jqSCuk0AdIfKN83CHhsuS2S6SECE
"""

print('ggg')

prob_M = [0.09,0.09,0.09,0.09,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04,0.04]
prob_K = [0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05]

table = [[3,11,17,19,12,6,2,15,13,14,1,18,5,0,16,8,10,7,4,9],
         [17,5,6,15,12,10,8,16,4,0,7,2,3,18,11,1,13,19,9,14],
         [13,15,8,6,7,11,18,2,10,14,17,4,1,19,12,16,3,0,5,9],
         [15,7,10,19,5,0,14,3,11,6,12,9,17,18,2,13,4,16,1,8],
         [9,4,1,7,6,2,14,0,13,8,5,3,19,18,11,12,10,16,15,17],
         [17,2,16,7,15,6,1,18,10,3,9,4,19,5,11,12,14,8,13,0],
         [13,10,19,4,18,2,7,9,15,16,3,1,17,11,6,12,8,0,5,14],
         [11,4,1,16,9,13,19,8,18,5,15,10,3,7,0,17,14,2,6,12],
         [16,19,6,10,0,15,7,13,4,2,14,3,17,5,18,11,1,9,8,12],
         [1,12,14,15,2,19,0,3,7,6,8,18,4,11,10,5,9,13,16,17],
         [8,2,6,5,18,16,9,1,19,17,15,7,0,10,4,3,14,13,12,11],
         [11,2,13,7,18,8,9,1,14,12,4,17,10,15,16,6,0,3,19,5],
         [16,3,6,18,11,8,17,15,13,10,5,2,1,7,12,19,4,9,0,14],
         [12,4,0,8,13,10,9,6,17,3,1,14,16,15,5,19,18,11,7,2],
         [12,10,17,2,6,16,3,15,9,13,4,1,19,14,11,0,8,18,7,5],
         [19,16,10,7,8,14,15,1,6,13,5,12,4,11,17,3,18,0,2,9],
         [12,4,13,17,10,9,0,15,2,19,16,1,7,5,11,8,6,14,3,18],
         [15,8,3,12,1,14,10,11,17,16,9,4,5,6,0,7,19,13,2,18],
         [11,3,12,7,1,2,9,14,4,17,6,19,8,10,16,18,0,5,13,15],
         [2,9,18,15,0,6,16,13,12,4,19,10,11,1,7,17,3,8,5,14]
]

# Порахуємо розподіл P(C)
total = 400 # общее количество шифротекстов
keys_probability = {}
for i in range(20):
  keys_probability[i] = 0
for i in range(len(table)):
  for j in range(len(table[i])):
    keys_probability[table[i][j]]+=prob_M[i]*prob_K[j]
print(keys_probability)
C = []
for i in range(len(keys_probability)):
  C.append(keys_probability[i])
for i in range(len(C)):
  C[i] = 0.05

# Порахуємо розподіл P(C, M)
CM_probability = [0]*20
for i in range(20):
  CM_probability[i] = [0]*20
for i in range(len(table)):
  for j in range(len(table[i])):
    CM_probability[table[i][j]][j]+=prob_M[j]*prob_K[i]
print(CM_probability)

print('')
sum = 0
for i in range(20):
  for j in range(20):
    sum+= CM_probability[i][j]
print(sum)

# Инвертировали в распределение P(M,C)
MC_probability = [0]*20
for i in range(20):
  MC_probability[i] = [0]*20
for i in range(20):
  for j in range(20):
    MC_probability[i][j] = CM_probability[j][i]
print(MC_probability)


pmc = [0]*20
for i in range(20):
  pmc[i] = [0]*20
for i in range(20):
  for j in range(20):
    pmc[i][j] = round(MC_probability[i][j]/C[j], 2)
#print(pmc)
for i in range(len(pmc)):
  print(pmc[i], end = '\n')

# Детерміністична вирішуюча функція
deterministic_decision_function = [0] * 20
p_cm = [ [0]*20 for i in range(20)]
for i in range(20):
  for j in range(20):
    p_cm[i][j] = pmc[j][i]
for i in range(len(p_cm)):
  print(p_cm[i], end = '\n')
for i in range(20):
  max_probability = max(p_cm[i])
  deterministic_decision_function[i] = p_cm[i].index(max_probability)
det_matrix = [0]*20
for i in range(20):
  det_matrix[i] = [0]*20
for i in range(20):
  det_matrix[i][deterministic_decision_function[i]] = 1
print('')
for i in range(len(det_matrix)):
  print(det_matrix[i], end = '\n')

#Функция потерь детерминистической функции
lost_det_function = 0
pmc_matrix = pmc.copy()
pcm = [[0]*20 for i in range(20)]
for i in range(20):
  for j in range(20):
    pcm[i][j] = pmc_matrix[j][i]
print('')
for i in range(20):
   print(pcm[i], end = '\n')
for i in range(20):
  lost_det_function+=C[i]*(1 - max(pcm[i]))
print(lost_det_function)

# Стохастическая функция

stochastic_decision_function = [0]*20
for i in range(20):
  stochastic_decision_function[i] = [0]*20
pcm_matrix = [ [0]*20 for i in range(len(stochastic_decision_function))]
for i in range(len(pmc)):
  for j in range(len(pmc[i])):
    pcm_matrix[i][j] = pmc[j][i]
max_matrix = [0 for i in range(20)]
for i in range(len(max_matrix)):
  max_matrix[i] = max(pcm_matrix[i])
stochastic_decision_function = pcm_matrix.copy()
for i in range(20):
  for j in range(20):
    if stochastic_decision_function[i][j]!=max_matrix[i]:
      stochastic_decision_function[i][j] = 0
M_sum = [0 for i in range(20)]
for i in range(20):
  for j in range(20):
    if stochastic_decision_function[i][j]!=0:
      M_sum[i]+=prob_M[j]
for i in range(20):
  for j in range(20):
    if stochastic_decision_function[i][j]!=0:
      stochastic_decision_function[i][j] = round(prob_M[j]/M_sum[i], 2)
for i in range(20):
  print(stochastic_decision_function[i], end = '\n') 

#Функция потерь стохастической функции
average_losses = [[0]*20 for i in range(20)]
for i in range(20):
  for j in range(20):
    average_losses[i][j] = round(1 - stochastic_decision_function[i][j], 2)
for i in range(20):
  print(average_losses[i], end = '\n')

result = 0
for i in range(20):
  for j in range(20):
    result = result + CM_probability[i][j]*average_losses[i][j]
print(result)
